### ISSUE TITLE
Environment creation error

### ISSUE THREAD

**Issue by CatChenal** [ericmjl/bayesian-stats-modelling-tutorial#83]
Following the local install instructions in the README, I end up with these errors:
```
(base) C:\folder_path\bayesian-stats-modelling-tutorial>conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: | b'Exception while loading config file C:\\me\\.jupyter\\jupyter_notebook_config.py\n    Traceback (most recent call last):\n      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\traitlets\\config\\application.py", line 563, in _load_config_files\n        config = loader.load_config()\n      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\traitlets\\config\\loader.py", line 457, in load_config\n        self._read_file_as_dict()\n      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\traitlets\\config\\loader.py", line 489, in _read_file_as_dict\n        py3compat.execfile(conf_filename, namespace)\n      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\ipython_genutils\\py3compat.py", line 198, in execfile\n        exec(compiler(f.read(), fname, \'exec\'), glob, loc)\n      File "C:\\me\\.jupyter\\jupyter_notebook_config.py", line 1\n        c.JupyterLabTemplates.template_dirs = [\'C:\\me\\Anaconda3\\envs\\dsml\\share\\jupyter\\notebook_templates\']\n                                              ^\n    SyntaxError: (unicode error) \'unicodeescape\' codec can\'t decode bytes in position 2-3: truncated \\UXXXXXXXX escape\nEnabling notebook extension jupyter-js-widgets/extension...\n      - Validating: ok\n'

done
#
# To activate this environment, use
#
#     $ conda activate bayesian-modelling-tutorial
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
What did I miss?

**Comment by ericmjl** [comment]
Nothing went wrong here - go ahead and activate the environment!

**Comment by CatChenal** [comment]
Thanks for your prompt response, Eric.
Perhaps I should not have included the lines after 'done`. Also, I have added formatting to wrap the error output. Here is the Exception output (reformatted):
```
Executing transaction: | b'Exception while loading config file C:\\me\\.jupyter\\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\traitlets\\config\\application.py", line 563, in _load_config_files\
       config = loader.load_config()
      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\traitlets\\config\\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\traitlets\\config\\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\\me\\Anaconda3\\envs\\bayesian-modelling-tutorial\\lib\\site-packages\\ipython_genutils\\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, \'exec\'), glob, loc)
      File "C:\\me\\.jupyter\\jupyter_notebook_config.py", line 1
        c.JupyterLabTemplates.template_dirs = [\'C:\\me\\Anaconda3\\envs\\dsml\\share\\jupyter\\notebook_templates\']
    SyntaxError: (unicode error) \'unicodeescape\' codec can\'t decode bytes in position 2-3: truncated \\UXXXXXXXX escape\nEnabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok\n'
```

If I go ahead and activate, this is what I get:
```
(base) C:\folder_path\bayesian-stats-modelling-tutorial>conda activate bayesian-modelling-tutorial

C:\folder_path\bayesian-stats-modelling-tutorial>SET DISTUTILS_USE_SDK=1
C:\folder_path\bayesian-stats-modelling-tutorial>SET MSSdk=1
C:\folder_path\bayesian-stats-modelling-tutorial>SET platform=
C:\folder_path\bayesian-stats-modelling-tutorial>IF /I [AMD64] == [amd64] set "platform=true"
C:\folder_path\bayesian-stats-modelling-tutorial>IF /I [] == [amd64] set "platform=true"
C:\folder_path\bayesian-stats-modelling-tutorial>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )
C:\folder_path\bayesian-stats-modelling-tutorial>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"
ERROR: The system was unable to find the specified registry key or value.
C:\folder_path\bayesian-stats-modelling-tutorial>if "" == "" (set "VSINSTALLDIR=" )
C:\folder_path\bayesian-stats-modelling-tutorial>if "" == "" (
ECHO "WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
 GOTO End
)
"WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
The system cannot find the batch label specified - End

(bayesian-modelling-tutorial) C:\folder_path\bayesian-stats-modelling-tutorial>
```
Something went wrong?

**Comment by ericmjl** [comment]
Hmmm...

I'm not sure how to debug this, as I've not been a Windows user for a very long time now, so the bad ways that Windows handles strings and the likes, and the differing idioms between the Windows  and *nix command lines, and finally the differing C compilers, make it difficult for me to debug this.

The only suggestion I can think of right now is to ask on JupyterLab's issue tracker for help (from reading the errors, issues are showing up because of Jupyter). Hope you find an answer with them, or at least the next issue tracker to try.
